name: Android CI

on:
  push:
    branches: [ "architecture-test" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Build with Gradle Global
      run: gradle assembleDebug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ViyuMessage-Premium-v1.0.0.2
        path: app/build/outputs/apk/debug/app-debug.apk
